#!/usr/bin/env php
<?php

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

require_once 'bootstrap.php';
require_once 'vendor/d11wtq/boris/lib/autoload.php';

$container = new ContainerBuilder();

$loader = new YamlFileLoader($container, new FileLocator(APP_ROOT . '/src/config'));
$loader->load('services.yml');
$container->compile();

/** @var \Symfony\Component\Console\Application $app */
$app = $container->get('app');
$boris = new \Boris\Boris('tp> ');
$boris->setLocal(['app' => $app, 'container' => $container]);
$boris->start();
