services:
  app:
    class: 'Symfony\Component\Console\Application'
    arguments: ['TargetPHProcess', '0.1-dev']

  app.command.init:
    class: 'TargetPHProcess\Command\Configuration\InitCommand'
    tags:
      -  { name: console.command }
    autowire: true

  app.command.auth_configuration:
    class: 'TargetPHProcess\Command\Configuration\AuthConfigurationCommand'
    tags:
      -  { name: console.command }
    autowire: true

  app.repositories.project:
    class: 'TargetPHProcess\DAL\Model\ProjectRepository'
    autowire: true
  app.repositories.time:
    class: 'TargetPHProcess\DAL\Model\TimeRepository'
    autowire: true
  app.repositories.userstory:
    class: 'TargetPHProcess\DAL\Model\UserStoryRepository'
    autowire: true
